<?php

/*
 * Laravel-Mns -- 阿里云消息队列（MNS）的 Laravel 适配。
 *
 * This file is part of the abe/laravel-mns.
 *
 * (c) Abraham Greyson <82011220@qq.com>
 * @link: https://github.com/abrahamgreyson/laravel-mns
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace LaravelMns\Test;

use AliyunMNS\Client;
use LaravelMns\MnsAdapter;
use Mockery as m;

class MnsAdapterTest extends AbstractTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testSetQueueProperlySetQueueName()
    {
        $defaultQueueName = 'default';
        $mnsClient = m::mock(Client::class)->makePartial();
        $mnsClient->shouldReceive('getQueueRef')
                  ->twice()
                  ->with(m::anyOf($defaultQueueName, 'anotherName'))
                  ->andReturn('whatever');
        $adapterUnderTest = new MnsAdapter($mnsClient, $defaultQueueName);
        $adapterUnderTest->setQueue('anotherName');
    }
}
