<?php

namespace LaravelMns\Test;

use AliyunMNS\Client;
use LaravelMns\MnsAdapter;
use Mockery as m;

class MnsAdapterTest extends AbstractTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testSetQueueProperlySetQueueName()
    {
        $defaultQueueName = 'default';
        $mnsClient = m::mock(Client::class)->makePartial();
        $mnsClient->shouldReceive('getQueueRef')
                  ->twice()
                  ->with(m::anyOf($defaultQueueName, 'anotherName'))
                  ->andReturn('whatever');
        $adapterUnderTest = new MnsAdapter($mnsClient, $defaultQueueName);
        $adapterUnderTest->setQueue('anotherName');
    }
}
